# /etc/rise.conf
# Rules are top-to-bottom; first match wins; default is deny.
# I wrote this easy for knuckleheads to understand.
# who     = user:test | group:wheel | user:test, group:wheel
# target  = root | any | nobody, root
# auth    = pam | none
# cmd     = any | /absolute/path, /another/path
# persist = default | yes | no
#
# Security:
#   chown root:root /etc/rise.conf
#   chmod 0600 /etc/rise.conf

[defaults]
format = 2

timestamp = yes
timestamp_timeout = 300
tty_tickets = yes
require_tty = no

jokes = on
secure_path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
env_keep = TERM,COLORTERM,LANG,LC_*

[rule block-guest]
action = deny
who = user:guest
target = any
cmd = any

[rule test-id-nopass]
action = allow
who = user:test
target = root
auth = none
cmd = /usr/bin/id, /usr/bin/true

[rule wheel-root]
action = allow
who = group:wheel
target = root
auth = pam
persist = default
cmd = any

[rule test-root]
action = allow
who = user:test
target = root
auth = pam
persist = default
cmd = any
